name: "Commitlint PR Title"
description: "Commitlints PR title input according to config"

inputs:
  github_pr_title:
    description: "GitHub PR title"
    default: ${{ github.event.pull_request.title }}

runs:
  using: composite

  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "22"

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        npm ci

    - name: Lint Commit
      id: validation
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "$PR_TITLE" | npx commitlint --config ${{ github.action_path }}/src/commitlint.config.js
      env:
        PR_TITLE: ${{ inputs.github_pr_title }}

branding:
  icon: "message-square"
  color: "gray-dark"
